### ISSUE TITLE
error timeout

### ISSUE THREAD

**Issue by juanpide** [CunningLogic/DUMLRacer#7]
I've tried to run 
java -jar DUMLRacer.jar AC
with Windows 10 on my Mavic Pro with firmware 1.4.100 but I get this error:

AC Mode

Choose target port: (* suggested port)
        [1] COM6 : USB Serial Device (COM6)
        [E] Exit
Choose port: 1
Using Port: COM6
Sending upgrade command
Uploading payload 1
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.commons.net.SocketClient._connect(SocketClient.java:243)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:202)
        at com.cunninglogic.dumlracer.Main.uploadFile(Main.java:343)
        at com.cunninglogic.dumlracer.Main.main(Main.java:129)

**Comment by ranqizhu** [comment]
Help needed...I am on osx, I am at the Dumlracer step 
java -jar DUMLRacer.jar AC

and I got this:

Using Port: cu.usbmodem141225
Sending upgrade command
Uploading payload 1
Exception in thread "main" org.apache.commons.net.ftp.FTPConnectionClosedException: Connection closed without indication.
 at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:324)
 at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:300)
 at org.apache.commons.net.ftp.FTP._connectAction_(FTP.java:438)
 at org.apache.commons.net.ftp.FTPClient._connectAction_(FTPClient.java:962)
 at org.apache.commons.net.ftp.FTPClient._connectAction_(FTPClient.java:950)
 at org.apache.commons.net.SocketClient._connect(SocketClient.java:244)
 at org.apache.commons.net.SocketClient.connect(SocketClient.java:202)
 at com.cunninglogic.dumlracer.Main.uploadFile(Main.java:343)
 at com.cunninglogic.dumlracer.Main.main(Main.java:129)﻿

**Comment by WolfgangMau** [comment]
👍 same problem here
OSX 10.13.6

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

Firmware V01.04.0500 
and downgraded to
Firmware V01.04.0200

**Comment by CunningLogic** [comment]
This is combo of user error, and PC setup error.

You guys are not selecting a DJI device. Either you dont have horndis installed and setup properly to network your drone to your pc, or your drone isnt plugged in, or something otherwise is keeping PC from talking to drone.

Closing as not an DR issue

**Comment by coaz** [comment]
Hello. Im getting the same message in windows with mini 2 and controller:

Choose target port: (* suggested port)
*	[1] COM3 : DJI USB Virtual COM (COM3)
	[E] Exit
Choose port: 1
Using Port: COM3
Sending upgrade command
Uploading payload 1
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.commons.net.SocketClient._connect(SocketClient.java:243)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:202)
	at com.cunninglogic.dumlracer.Main.uploadFile(Main.java:344)
	at com.cunninglogic.dumlracer.Main.main(Main.java:130)
